glider_dac/models/institution.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
glider_dac/models/institution.py
Model definition for Institution
'''
from datetime import datetime
from glider_dac.extensions import db


class Institution(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), unique=True)
    created = db.Column(db.DateTime(timezone=True), default=datetime.utcnow)
    updated = db.Column(db.DateTime(timezone=True))

glider_dac/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
glider_dac/views/index.py
'''
from flask import (render_template, make_response, redirect, flash, url_for,
                   request, current_app, Blueprint)
from glider_dac.models.institution import Institution
from glider_dac.models.user import User
from glider_dac.models.deployment import Deployment
from glider_dac.models.user import User
from glider_dac.extensions import db
from flask_login import login_user, logout_user, current_user
from flask_wtf import FlaskForm
from sqlalchemy import select, func
from wtforms import StringField, PasswordField

index_bp = Blueprint("index", __name__)

class LoginForm(FlaskForm):
    username = StringField('Name')
    password = PasswordField('Password')


@index_bp.route('/', methods=['GET'])
def index():
    deployments = Deployment.query.order_by(Deployment.created.desc()).limit(20)
    user_deployments = (db.session.execute(select(User.name,
                                 func.count(Deployment.name)).join(User)
                                 .group_by(Deployment.user_id)).all())

    operator_deployments = (db.session.execute(
                                    select(Deployment.operator, func.count())
                                    .group_by(Deployment.operator)).all())

    return render_template('index.html',
                           deployments=deployments,
                           user_deployments=user_deployments,
                           operator_deployments=operator_deployments)


@index_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_active:
        flash("Already logged in", 'warning')
        return redirect(request.args.get("next") or url_for("index.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.authenticate(form.username.data, form.password.data)
        if not user:
            flash("Failed", 'danger')
            return redirect(url_for("index.login"))

        login_user(user)
        flash("Logged in successfully", 'success')
        return redirect(request.args.get("next") or url_for("index.index"))
    response = make_response(render_template("login.html", form=form))
    return response


@index_bp.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for("index.index"))


def serialize_date(date):
    if date is not None:
        return date.isoformat()


@index_bp.route('/site-map')
def site_map():
    '''
    Returns a json structure for the site routes and handlers
    '''
    links = []
    for rule in current_app.url_map.iter_rules():
        # Filter out rules we can't navigate to in a browser
        # and rules that require parameters
        if "GET" in rule.methods and has_no_empty_params(rule):
            url = url_for(rule.endpoint)
            links.append((url, rule.endpoint))
    # links is now a list of url, endpoint tuples
    return jsonify(rules=links)


@index_bp.route('/crossdomain.xml', methods=['GET'])
def crossdomain():
    domain = """
    <cross-domain-policy>
        <allow-access-from domain="*"/>
        <site-control permitted-cross-domain-policies="all"/>
        <allow-http-request-headers-from domain="*" headers="*"/>
    </cross-domain-policy>
    """
    response = make_response(domain)
    response.headers["Content-type"] = "text/xml"
    return response

glider_dac/views/institution.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
glider_dac/views/institution.py
View definition for institutions
'''

from flask import (current_app, render_template, redirect, flash, url_for,
                   jsonify, request, Blueprint)
from flask_cors import cross_origin
from flask_login import current_user
from glider_dac import db
from glider_dac.models.institution import Institution
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from functools import wraps
import json


institution_bp = Blueprint("institution", __name__)

def error_wrapper(func):
    '''
    Function wrapper to catch exceptions and return them as jsonified errors
    '''
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            return jsonify(error=type(e).__name__, message=e.message), 500
    return wrapper


def admin_required(func):
    '''
    Wraps a route to require an administrator
    '''
    @wraps(func)
    def wrapper(*args, **kwargs):
        if current_app.login_manager._login_disabled:
            return func(*args, **kwargs)
        elif not current_user.is_authenticated:
            return app.login_manager.unauthorized()
        elif not current_user.admin:
            flash("Permission denied", 'danger')
            return redirect(url_for('index.index'))
        return func(*args, **kwargs)
    return wrapper


class NewInstitutionForm(FlaskForm):
    name = StringField('Institution Name')
    submit = SubmitField('New Institution')


@institution_bp.route('/institutions/', methods=['GET', 'POST'])
@admin_required
def show_institutions():
    institutions = Institution.query.all()
    form = NewInstitutionForm()
    if form.validate_on_submit():
        institution = Institution()
        institution.name = form.name.data
        institution.save()
        db.session.add(institution)
        db.session.commit()
        flash('Institution Created', 'success')

    return render_template('institutions.html',
                           form=form,
                           institutions=institutions)


@institution_bp.route('/api/institution', methods=['GET'])
@cross_origin()
def get_institutions():
    institutions = [json.loads(inst.to_json()) for inst in Institution.query.all()]
    return jsonify(results=institutions)


@institution_bp.route('/api/institution', methods=['POST'])
@admin_required
@error_wrapper
def new_institution():
    current_app.logger.info(request.data)
    data = json.loads(request.data)
    institution = Institution()
    institution.name = data['name']
    institution.save()
    db.session.add(institution)
    db.session.commit()
    return institution.to_json()


@institution_bp.route('/api/institution/<string:institution_id>',
                      methods=['DELETE'])
@admin_required
@error_wrapper
def delete_institution(institution_id):
    if not current_user.admin:
        flash("Permission denied", 'danger')
        return redirect(url_for('index.index'))
    institution = Institution.query.filter_by(institution_id=institution_id).one_or_none()
    if institution is None:
        return jsonify({}), 404
    current_app.logger.info(f"Deleting institution {institution.name}")
    db.session.delete(institution)
    db.session.commit()
    return jsonify({}), 204

glider_dac/views/user.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
glider_dac/views/user.py
View definitions for Users
'''
from flask import (render_template, redirect, flash, url_for, request,
                   Blueprint, current_app)
from sqlalchemy import func
from flask_login import login_required, current_user
from glider_dac import db
from glider_dac.models.user import User
from flask_wtf import FlaskForm
from glider_dac.models.deployment import Deployment
from wtforms import validators, StringField, PasswordField, SubmitField
from wtforms.form import BaseForm
from passlib.hash import sha512_crypt


class UserForm(FlaskForm):
    username = StringField('Username')
    name = StringField('Name')
    password = PasswordField('Password', [
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Confirm Password')
    organization = StringField('Organization')
    email = StringField('Email')
    submit = SubmitField("Submit")


user_bp = Blueprint("user", __name__)


@user_bp.route('/users/<string:username>', methods=['GET', 'POST'])
@login_required
def edit_user(username):
    current_app.logger.info("GET %s", username)
    current_app.logger.info("Request URL: %s", request.url)
    user = User.query.filter_by(username=username).one_or_none()
    if user is None or (user is not None and not current_user.admin and
                        current_user != user):
        # No permission
        current_app.logger.error("Permission is denied")
        current_app.logger.error("User: %s", user)
        current_app.logger.error("Admin?: %s", current_user.admin)
        current_app.logger.error("Not current user?: %s", current_user != user)
        flash("Permission denied", 'danger')
        return redirect(url_for("index"))

    form = UserForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)
        user.save()
        if form.password.data:
            user.password = sha512_crypt.hash(form.password.data)
        db.session.commit()
        flash("Account updated", 'success')
        return redirect(url_for("index.index"))

    return render_template('edit_user.html', form=form, user=user)


@user_bp.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if not current_user.admin:
        # No permission
        flash("Permission denied", 'danger')
        return redirect(url_for("index.index"))

    form = UserForm()

    if (form.is_submitted() and
        BaseForm.validate(form,
                          extra_validators={'password':
                                            [validators.InputRequired()]})):
        user = User()
        form.populate_obj(user)
        user.save()
        user.password = sha512_crypt.hash(form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Account for '%s' created" % user.username, 'success')
        return redirect(url_for("user.admin"))

    subquery = db.session.query(
        Deployment.user_id.label("user_id"),
        func.count().label('deployments_count')
    ).group_by(Deployment.user_id).subquery()

    # Query to join User table with the subquery
    user_deployment_counts = db.session.query(
        User.username,
        User.name,
        User.email,
        User.organization,
        subquery.c.deployments_count
    ).join(subquery, subquery.c.user_id == User.id).all()

    current_app.logger.info(user_deployment_counts[0])

    return render_template('admin.html', form=form,
                           deployment_counts=user_deployment_counts)


# TODO: Merge with regular admin editing page
@user_bp.route('/admin/<string:username>', methods=['GET', 'POST'])
@login_required
def admin_edit_user(username):
    if not current_user.admin:
        # No permission
        flash("Permission denied", 'danger')
        return redirect(url_for("index.index"))

    user = User.query.filter_by(username=username).one_or_none()

    form = UserForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)
        # TODO: update application
        user.save()
        db.session.commit()
        if form.password.data:
            user.password = sha512_crypt.hash(form.password.data)
        flash("Account updated", 'success')
        return redirect(url_for("user.admin"))

    return render_template('edit_user.html', form=form, user=user)


@user_bp.route('/admin/<string:username>/delete', methods=['POST'])
@login_required
def admin_delete_user(username):
    if not current_user.admin:
        # No permission
        flash("Permission denied", 'danger')
        return redirect(url_for("index.index"))

    user = User.query.filter_by(username=username).one_or_none()

    if user._id == current_user._id:
        flash("You can't delete yourself!", "danger")
        return redirect(url_for("user.admin"))

    # TODO: is this a valid SQLAlchemy method?
    user.delete()
    db.session.commit()

    flash("User deleted", "success")
    return redirect(url_for('user.admin'))

glider_dac/templates/_deployment_files.html
{% for f in files %}
  <tr>
    {% if editable %}
    <td><input type="checkbox" /></td>
    {% endif %}
    <td>{{ f[0] }}</td>
    <td data-value="{{ f[1] }}"><abbr title="{{ f[1] | datetimeformat }} UTC">{{ f[1] | prettydate }}</abbr></td>
  </tr>
{% endfor %}

glider_dac/templates/admin.html
{% from "macros.html" import render_field %}
{% extends "layout.html" %}

{% block title %}Admin{% endblock %}
{% block page %}

<div class="row">
  <div class="col-lg-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Username</th>
          <th>Name</th>
          <th>Email</th>
          <th>Organization</th>
          <th>Deployments</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
      {%- for user in user_deployment_counts %}
      <tr>
        <td>{{user.username}} {% if user.admin %}<span class="label label-success">ADMIN</span>{% endif %}</td>
        <td>{{user.name}}</td>
        <td>{{user.email}}</td>
        <td>{{user.organization}}</td>
        <td>
          {% if '_id' in deployment_counts %}
          <a href="{{ url_for('deployment.list_user_deployments', username=user.username) }}"><span class="label label-success">{{ deployment_counts.get(user._id, '0') }}</span></a>
          {% else %}
            <span class="label label-default">0</span>
          {% endif %}
        </td>

        <td>
          <a href="{{ url_for('user.admin_edit_user', user_id=user._id) }}" class="btn btn-default btn-xs">Edit</a>
          <form class="form form-inline" style="display: inline" method="POST" action="{{ url_for('user.admin_delete_user', user_id=user._id) }}">
            {{ form.hidden_tag() }}
            <button class="btn btn-danger btn-xs">Delete</button>
          </form>
        </td>
      </tr>
      {%- endfor %}
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('form button').on('click', function(e) {
      if (!confirm("Are you sure you want to delete this user?")) {
        event.preventDefault();
      }
    });
  });
</script>

<div class="row">

<div class="col-lg-6">
  <h3>Add New User</h3>
  <form class="form" style="margin:0px;" method="POST" action="{{ url_for('user.admin') }}">
    {{ form.hidden_tag() }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}
    {{ render_field(form.name) }}
    {{ render_field(form.email) }}
    {{ render_field(form.organization) }}
    {{ form.submit(class_="btn btn-primary") }}
  </form>
</div>
</div>
{% endblock %}

glider_dac/templates/edit_user.html
{% from "macros.html" import render_field %}
{% extends "layout.html" %}

{% block title %}Editing {{ user.username }}{% endblock %}

{% block page %}

<h3>Editing {{ user.username }}</h3>

  <div class="col-lg-6">
  <form name="user_edit" id="user_edit" method="POST" action="{{ action_path }}">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.email) }}
    {{ render_field(form.organization) }}
    {{ render_field(form.password, False, "If you do not want to change passwords, leave this blank.") }}
    {{ render_field(form.confirm) }}
    {{ form.submit(class_="btn btn-primary") }}
  </form>
</div>

{% endblock %}

glider_dac/templates/index.html
{% extends "layout.html" %}

{% block title %}Main{% endblock %}

{% block page %}

<div class="row">
  <div class="col-lg-8">
    <h3>Deployments</h3>
    <table class="table table-bordered table-striped sortable">
      <thead>
        <tr>
          <th data-defaultsort="asc">Deployment</th>
          <th>WMO ID</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
      {%- for m in deployments %}
      <tr>
        <td class="col-lg-4"><a href="{{ url_for('deployment.show_deployment', deployment_name=m.name) }}">{{ m.name }}</a></td>
        <td class="col-lg-4">{{ m.wmo_id }}</td>
        <td class="col-lg-4"><abbr title="{{ m.created | datetimeformat }} UTC">{{ m.created | prettydate }}</abbr></td>
      </tr>
      {%- endfor %}
      </tbody>
    </table>
  </div>

  <div class="col-lg-4">
    <h3>Operators</h3>
    <ul class="list-group">
      {%- for u in operator_deployments %}
      {%- if u[0] %}
      <li class="list-group-item">
      <span class="badge">{{ u[1] }} deployment{{ u[1]|pluralize('', 's')}}</span>
      {# <a href="_blank"> #}
        <a href="{{ url_for('deployment.list_operator_deployments',
                            operator=u[0] if u[0] is not none else "Unspecified") }}">
          {{ u[0] }}
        </a>
      </li>
      {%- endif %}
      {%- endfor %}
    </ul>

    <h3>Contributors</h3>
    <ul class="list-group">
      {%- for u in user_deployments %}
      <li class="list-group-item">
        <span class="badge">{{ u['count'] }} deployment{{ u['count']|pluralize('', 's')}}</span>
        <a href="{{ url_for('deployment.list_user_deployments', username=u.user_id) }}">
          {{ u.name }}
        </a>
      </li>
      {%- endfor %}
    </ul>
  </div>
</div>

{% endblock %}

glider_dac/templates/institutions.html
{% extends "layout.html" %}
{% block title %}Institutions{% endblock %}

{% block page %}

<div id="new-institution-form">
  <form class="form-inline" method="POST" action="{{url_for('institution.show_institutions')}}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.name(id="institution-name", placeholder="Institution Name", class_="form-control") }}
    </div>
    <button id="new-institution" type="submit" class="btn btn-default">New Institution</button>
  </form>
</div>

<div class="row">
  <div class="col-lg-8">
    <h3>Institutions</h3>
    <table class="table table-bordered table-striped sortable">
      <thead>
        <tr>
          <th>Institution</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {%- for inst in institutions %}
        <tr>
          <td>{{inst.name}}</td>
          <td>
            <a class="delete-institution" data-institution="{{inst._id}}" href="#">
              Delete
            </a>
          </td>
        </tr>
        {%- endfor %}
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript">
$(function() {
  $('.delete-institution').click(function(event) {
    var getUrl = function(institution_id) {
      return "{{ url_for('institution.delete_institution', institution_id='institution_id') }}".replace(/institution_id/, institution_id);
    };

    $.ajax({
      dataType: "json",
      type: "DELETE",
      url: getUrl($(event.target).data('institution')),
      success: function(result) {
        window.location.reload();
      },
      error: function(request, msg, error) {
      }
    });
  });

  $('#new-institution').click(function(event) {
    event.stopPropagation();
    event.preventDefault();

    $.ajax({
      dataType: "json",
      type: "POST",
      url: "{{url_for('institution.new_institution')}}",
      contentType: "application/json;charset=utf-8",
      data: JSON.stringify({name: $('#institution-name').val()}),
      success: function(result) {
        window.location.reload();
      },
      error: function(jqXHR, status, error) {
        console.error(jqXHR);
        console.error(status);
        console.error(error);
      }
    });

  });

});
</script>
{% endblock %}

glider_dac/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Glider DAC - {% block title %}{% endblock %}</title>
    {%- block javascript %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
    {%- endblock %}
    {%- block css %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/glider-style.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap-sortable.css') }}">
    {% if config.GA_ENABLED -%}
      <!-- Global site tag (gtag.js) - Google Analytics -->

      <script async src="https://www.googletagmanager.com/gtag/js?id={{ config.GA_TAG_ID }}"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '{{ config.GA_TAG_ID }}');
      </script>
    {% endif %}
    {%- endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-img-brand" href="http://ioos.noaa.gov/">
            <img src="{{ url_for('static', filename='img/ioos.png') }}" alt="IOOS Glider DAC" />
          </a>
          <a class="navbar-brand" href="http://gliders.ioos.us/providers/">
            Glider DAC v2
          </a>
        </div>
        <ul class="navbar-nav nav">
          {%- if current_user.is_active %}
          <li><a href="{{ url_for('deployment.list_user_deployments', username=current_user.username) }}">Your Deployments</a></li>
          {%- endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%- if current_user.is_active %}
            {%- if current_user.admin %}
            <li><p class="navbar-text"><a href="{{url_for('user.admin')}}"><span class="label label-success">ADMIN</span></a></p></li>
            {%- endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.username }} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user.edit_user', username=current_user.username) }}">Account</a></li>
                <li><a href="{{ url_for('index.logout') }}">Logout</a></li>
              </ul>
            </li>
          {%- else %}
            <li><a href="{{ url_for('index.login') }}">Login</a></li>
          {%- endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {%- with messages = get_flashed_messages(with_categories=true) %}
        {%- if messages %}
          {%- for category, message in messages %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {%- endfor %}
        {%- endif %}
      {%- endwith %}


      {%- block page %}{%- endblock %}

    </div>

    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-sortable.js') }}"></script>
  </body>
</html>

glider_dac/templates/login.html
{% extends "layout.html" %}

{% block page %}

<h3>Login</h3>

<form class="form-horizontal" method="POST" action="{{ url_for('index.login') }}">
  {{ form.csrf_token }}
  {% if form.csrf_token and form.csrf_token.errors %}
      <div class="warning">You have submitted an invalid CSRF token</div>
  {% endif %}

  {% for field in form %}
  {% if field.name != "csrf_token" %}
  <div class="control-group">
    <label class="control-label" for="{{ field.name }}">{{ field.label }}</label>
    <div class="controls">
      {{ field() }}
      {% if field.description %}
      <span class="help-block">{{ field.description }}</span>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% endfor %}
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Login</button>
  </div>
</form>

{% endblock %}

glider_dac/templates/macros.html
{% macro render_field(field, static=False, help=None) %}
  <div class="form-group {{ "has-error" if field.errors }}">
    {% if field.label is defined %}
      <label for="{{ field.name }}" class="control-label">
        {{ field.label }}
        {% if field.errors %}
          <ul class=errors>
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
          </ul>
        {% endif %}
      </label>
    {% endif %}
    {% if static %}
      <p class="form-static-control">{{ field.object_data or "&nbsp;"|safe }}</p>
    {% else %}
      {{ field(class_="form-control", **kwargs)|safe }}
    {% endif %}
    {% if help %}
      <span class="help-block">{{ help }}</span>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_boolean(field, static=False, title='') %}
  <div class="form-group">
    {% if static %}
    {{ field(disabled=True, **kwargs)|safe }}
    {% else %}
    {{ field(**kwargs)|safe }}
    {% endif %}

    {% if field.label is defined %}
      <label for="{{ field.name }}" title="{{ title }}"" class="control-label">
        {{ field.label }}
      {% if field.errors %}
        <ul class=errors>
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </ul>
      {% endif %}
      </label>
    {% endif %}
  </div>
{% endmacro %}

glider_dac/templates/operator_deployments.html
{% extends "layout.html" %}

{% block title %}{{ operator }}'s deployments{% endblock %}

{% block page %}

<h3>Deployments for {{ operator }}</h3>

<div class="">
  <table class="table table-striped sortable">
    <thead>
      <tr>
        <th data-defaultsort='asc'>Deployment</th>
        <th>Contributor</th>
        <th>WMO ID</th>
        <th>Attribution</th>
        <th>Last Updated</th>
      </tr>
    </thead>
    <tbody>
    {%- for m in deployments %}
    <tr>
      <td><a href="{{ url_for('deployment.show_deployment', username='none', deployment_name=m.name) }}">{{ m.name }}</a></td>
      <td><a href="{{ url_for('deployment.list_user_deployments', username=m.username) }}">{{ m.username }}</a></td>
      <td>{{ m.wmo_id }}</td>
      <td>{{ m.attribution }}</td>
      <td data-value="{{ m.updated }}"><abbr title="{{ m.updated | datetimeformat }} UTC">{{ m.updated | prettydate }}</abbr></td>
    </tr>
    {%- endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

glider_dac/templates/user_deployments.html
{% from "macros.html" import render_field, render_boolean %}
{% extends "layout.html" %}

{% block title %}{{ username }}'s deployments{% endblock %}

{% block page %}

<h3>Deployments for {{ username }}</h3>

{% if form %}

<div id="new-deployment-form" class="" style="">
  <form class="form form-inline" style="margin:0px;" method="POST" action="{{ url_for('deployment.new_deployment', username=username) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.glider_name(placeholder="Glider Name", class_="form-control") }}
    </div>
    <div class="form-group">
      {{ form.deployment_date(placeholder="YYYY-MM-DDTHH:mmZ", class_="form-control datepicker") }}
    </div>
    <div class="form-group">
      {{ form.attribution(placeholder="Attribution", class_="form-control") }}
    </div>
    <div class="form-group">
      {{ render_boolean(form.delayed_mode, False, "Check if this deployment is delayed mode data") }}
    </div>
    <button type="submit" class="btn btn-primary" disabled="disabled"><span class="glyphicon glyphicon-plus"></span> New Deployment</button>
  </form>
</div>

<script type="text/javascript">
$(function() {
  var gliderNameDfd = $.Deferred();
  var dateDfd = $.Deferred();
  $('#new-deployment-form input[name="glider_name"]').on('input', function (e) {
    gliderNameDfd.resolve();
  });
  $('#new-deployment-form input[name="deployment_date"]').on('input', function (e) {
    dateDfd.resolve();
  });
  $.when(gliderNameDfd, dateDfd).done(function() {
    var btn = $('#new-deployment-form button');
    btn.prop('disabled', false);
  });
});
</script>
<br/>
{% endif %}

<div class="">
  <table class="table table-striped sortable">
    <thead>
      <tr>
        <th data-defaultsort='asc'>Deployment</th>
        <th>Operator</th>
        <th>Last Updated</th>
      </tr>
    </thead>
    <tbody>
    {%- for m in deployments %}
    <tr>
      <td><a href="{{ url_for('deployment.show_deployment', username=username, deployment_name=m.name) }}">{{ m.name }}</a></td>
      <td>{% if m.operator %}<a href="{{ url_for('deployment.list_operator_deployments', operator=m.operator) }}">{{ m.operator }}{% endif %}</a></td>
      <td data-value="{{ m.updated }}"><abbr title="{{ m.updated | datetimeformat }} UTC">{{ m.updated | prettydate }}</abbr></td>
      <td>
        {% if form and not m.delayed_mode%}
          <form class="form form-inline" style="display: inline" method="POST" action="{{ url_for('deployment.new_delayed_mode_deployment', username=username, deployment_name=m.name) }}">
            {{ form.hidden_tag() }}
            <button title="Submit delayed mode data for this deployment" class="btn btn-primary btn-xs" {{ disabled }}><span class="glyphicon glyphicon-plus"></span> Delayed Mode</button>
          </form>
        {% endif %}
      </td>
    </tr>
    {%- endfor %}
    </tbody>
  </table>
</div>

{% endblock %}